apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "istio-authorizer.fullname" . }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
data:
  config.yaml: |
    logging:
      level: {{ .Values.logging.level }}
    discovery:
      enabled: {{ .Values.discovery.enabled }}
      namespaces:
      {{- range .Values.discovery.namespaces }}
      - {{ . }}
      {{- end }}
      timeout: {{ .Values.discovery.timeout }}
      interval: {{ .Values.discovery.interval }}
      disable_proxy: {{ .Values.discovery.disableProxy }}
      open_api_endpoint: {{ .Values.discovery.openApiEndpoint }}
      grpc_refrection_calls: {{ .Values.discovery.grpcRefrectionCalls }}
    do_not_fail_on_non_matching_requests: {{ .Values.doNotFailOnNonMatchingRequests }}
    cluster_domain: {{ .Values.clusterDomain }}
    headers:
      output_header_prefix: {{ .Values.headers.outputHeaderPrefix }}
      auth_ctx_header: {{ .Values.headers.authCtxHeader }}
    token_exchange:
      enabled: {{ .Values.tokenExchange.enabled }}
      cache:
        ttl: {{ .Values.tokenExchange.cache.ttl }}
        max_size: {{ .Values.tokenExchange.cache.maxSize }}
    inject_token:
      mode: {{ .Values.injectToken.mode }}
      original_token_header_name: {{ .Values.injectToken.originalTokenHeaderName }}
      exchanged_token_header_name: {{ .Values.injectToken.exchangedTokenHeaderName }}
      strip_bearer: {{ .Values.injectToken.stripBearer }}
{{- range $key, $value := .Values.data }}
  {{- if eq $key "extraconfig" }}
  {{ $key }}.yaml: {{ toYaml $value | indent 4 }}
  {{ else }}
  {{ $key }}: {{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}
