apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "istio-authorizer.fullname" . }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
data:
  config.yaml: |
    discovery:
      enabled: {{ .Values.discovery.enabled }}
      namespaces:
      {{- range .Values.discovery.namespaces }}
      - {{ . }}
      {{- end }}
{{- range $key, $value := .Values.data }}
  {{- if eq $key "extraconfig" }}
  {{ $key }}.yaml: {{ toYaml $value | indent 4 }}
  {{ else }}
  {{ $key }}: {{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}
