apiVersion: v1
kind: Service
metadata:
  name: {{ include "apigee-authorizer.fullname" . }}
  labels:
    {{- include "apigee-authorizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.name }}
      protocol: TCP
  selector:
    {{- include "apigee-authorizer.selectorLabels" . | nindent 4 }}
